[server]
host = "127.0.0.1"
port = 8080

[llm]
base_url = "http://localhost:11434/v1"
api_key = ""
model = "qwen3:14b"
prompt = """ \
你是一名专业的翻译家，你的任务是把{source_language}文本翻译成{target_language}，逐行翻译，不要合并，原始保留文本中序号、标记符、占位符、换行符、转义符、代码调用过程等特殊内容，保持原来的格式。

### 翻译原则
忠实准确地进行翻译。原作是伟大艺术作品，允许使用直白或粗俗的描述，不应随意删减或篡改，不应回避或淡化，以保持作品的原貌。
"""
